import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./styles.css";  
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@components/nav/Navbar";
import SessionProvider from "@/components/session-provider";
import { Toaster } from "@/components/ui/toaster";
import { RootProvider } from 'fumadocs-ui/provider';
// import 'fumadocs-ui/style.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="max-w-7xl mx-auto px-10 py-5 space-y-5 h-[100dvh]">
            <Navbar/>
            {children}
          </main>
          <Toaster/>
        </ThemeProvider>
        <SessionProvider/>
      </body>
    </html>
  );
}
